### ISSUE TITLE
[Feature]: Don't use common or "default" container names like db by default

### ISSUE THREAD

**Issue by C-Fu** [crocofied/PortNote#11]
### Feature Summary

Lots of examples out there are using container names like web,db,etc in their docker-compose

### Motivation

Lots of examples out there are using container names like web,db, and other common names in their docker-compose file, which leads to unnecessary issues and errors. We (I personally) are sorta-kinda annoyed (for a lack of a better word) when an older or more popular container have already.... "associated" itself with a particular "easy" port (like 8080, 33400), and then something else comes along that also uses the same ports, but I am more... "annoyed) by the use of basic/common words as the container name, in which both leads to errors.

I understand that both are easily solvable, but I'd prefer to copy the compose file and run/test it straight away instead of checking the ports or names, lack of security notwithstanding.

### Possible Solution

Instead I propose something like this to replace the current docker-compose.yml:
```
services:
  portnote-web: #or even just portnote is fine!
    image: haedlessdev/portnote:latest
    container_name: portnote-web
    ports:
      - "3003:3000" #3003 is not so popular compared to 3000
    environment:
      JWT_SECRET: <RANDOM-256-CHARACTER-STRING> # Replace with a secure random string
      USER_SECRET: <RANDOM-256-CHARACTER-STRING> # Replace with a secure random string
      LOGIN_USERNAME: yourusername # Replace with a username
      LOGIN_PASSWORD: UseAGoodPassword # Replace with a custom password
      DATABASE_URL: "postgresql://postgresuser:UseAGoodPostGresPassword@portnote-db:5432/portnotedb" #not sure if it has to be /portnotedb

  portnote-agent:
    image: haedlessdev/portnote-agent:latest
    container_name: portnote-agent
    environment:
      DATABASE_URL: "postgresql://postgresuser:UseAGoodPostGresPassword@portnote-db:5432/portnotedb"

  portnote-db:
    container_name: portnote-db
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: UseAGoodPostGresPassword
      POSTGRES_DB: portnotedb
    volumes:
      - ./portnote-db:/var/lib/postgresql/data
```

This way (usability-wise, I think) there is an incentive to actually change the password(s) instead of using a standard "password" I reckon.

Just a humble suggestion, keep up the awesome work dude! Can't wait to be able to export the notes into markdown or .docx or whatever!
