### ISSUE TITLE
[Bug]: Komodo + Portnote unable to access the app

### ISSUE THREAD

**Issue by Eldritzh** [crocofied/PortNote#29]
### What happened?

Changed the port as it's already being used by Karakeep, when running it is unreachable, and the logs tells me it seems to be due to postgres db

### Steps to reproduce

1: add stack to Komodo using UI function.
2: Change port etc
3: Get image
4: Log should say issue with db

### Operating System

Linux

### Version

Latest

### Logs

db-1     | PostgreSQL init process complete; ready for start up. db-1     |  db-1     | 2025-05-15 11:01:08.477 UTC [1] LOG:  starting PostgreSQL 17.5 (Debian 17.5-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit db-1     | 2025-05-15 11:01:08.478 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432 db-1     | 2025-05-15 11:01:08.478 UTC [1] LOG:  listening on IPv6 address "::", port 5432 db-1     | 2025-05-15 11:01:08.515 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432" db-1     | 2025-05-15 11:01:08.562 UTC [61] LOG:  database system was shut down at 2025-05-15 11:01:08 UTC db-1     | 2025-05-15 11:01:08.583 UTC [1] LOG:  database system is ready to accept connections db-1     | 2025-05-15 11:02:03.939 UTC [1] LOG:  received fast shutdown request db-1     | 2025-05-15 11:02:03.963 UTC [1] LOG:  aborting any active transactions db-1     | 2025-05-15 11:02:03.965 UTC [1] LOG:  background worker "logical replication launcher" (PID 64) exited with exit code 1 db-1     | 2025-05-15 11:02:03.965 UTC [59] LOG:  shutting down db-1     | 2025-05-15 11:02:04.000 UTC [59] LOG:  checkpoint starting: shutdown immediate db-1     | 2025-05-15 11:02:04.262 UTC [59] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.104 s, sync=0.027 s, total=0.297 s; sync files=2, longest=0.014 s, average=0.014 s; distance=0 kB, estimate=0 kB; lsn=0/14E5050, redo lsn=0/14E5050 db-1     | 2025-05-15 11:02:04.264 UTC [1] LOG:  database system is shut down db-1     |  db-1     | PostgreSQL Database directory appears to contain a database; Skipping initialization db-1     |  db-1     | 2025-05-15 11:02:05.110 UTC [1] LOG:  starting PostgreSQL 17.5 (Debian 17.5-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit db-1     | 2025-05-15 11:02:05.110 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432 db-1     | 2025-05-15 11:02:05.110 UTC [1] LOG:  listening on IPv6 address "::", port 5432 db-1     | 2025-05-15 11:02:05.155 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432" db-1     | 2025-05-15 11:02:05.194 UTC [29] FATAL:  the database system is starting up db-1     | 2025-05-15 11:02:05.197 UTC [28] LOG:  database system was shut down at 2025-05-15 11:02:04 UTC db-1     | 2025-05-15 11:02:05.231 UTC [1] LOG:  database system is ready to accept connections db-1     | 2025-05-15 11:07:05.297 UTC [26] LOG:  checkpoint starting: time db-1     | 2025-05-15 11:07:09.809 UTC [26] LOG:  checkpoint complete: wrote 46 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=4.342 s, sync=0.084 s, total=4.513 s; sync files=11, longest=0.024 s, average=0.008 s; distance=269 kB, estimate=269 kB; lsn=0/1528730, redo lsn=0/15286D8 db-1     | 2025-05-15 11:07:29.431 UTC [45] LOG:  could not receive data from client: Connection reset by peer

**Comment by vas-dav** [comment]
When the connection got reset it really looks like some network connectivity issue, hence I would first try to start over and reproduce the issue from clean slate. Empty directory, no predefined db.

**Comment by JoanComasFdz** [comment]
I had a very similar issue: Karakeep on 3000, then portnote wouldn't start.

I run:
```
> ip r | grep 192.168.128.0/24
192.168.128.0/24 dev br-1e4a62e37851  proto kernel  scope link  src 192.168.128.1 linkdown
192.168.128.0/24 dev br-ea874469eb20  proto kernel  scope link  src 192.168.128.1
```

According to ChatGPT, there seems to be some kind of race condition in docker when creating the NAT thing in docker.

I removed everything and the linkdown was still there.

I then run:
- `docker network prune`
- `sudo ip route del 192.168.128.0/24 dev br-1e4a62e37851`
- `sudo ip link delete br-1e4a62e37851 type bridge`

Then I modified the docker compose as follows:
- Remapped port for web to `4000:3000`.
- Reordered the services so that the web is the last one.
- Added a healthcheck to postgress so that the other services properly wait for it.
- Added a custom network and fixed IPs. I always do this in my NAS.
- Set custom paths for volumes. I always do this in my NAS.

Result:
```
networks:
  portnote_internet_ui_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.128.0/24
          gateway: 192.168.128.1


services:
  portnote-db:
    image: postgres:17
    container_name: portnote-db
    restart: always
    dns:
      - 192.168.1.53 #My pihole
      - 1.1.1.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - /share/DockerContainersSSD/portnote/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      portnote_internet_ui_net:
        ipv4_address: 192.168.128.4
  portnote-agent:
    image: haedlessdev/portnote-agent:latest
    container_name: portnote-agent
    dns:
      - 192.168.1.53
      - 1.1.1.1
    environment:
      DATABASE_URL: postgres://postgres:postgres@portnote-db:5432/postgres
    networks:
      portnote_internet_ui_net:
        ipv4_address: 192.168.128.3
    depends_on:
      portnote-db:
        condition: service_healthy 
  portnote-web:
    image: haedlessdev/portnote:latest
    container_name: portnote
    dns:
      - 192.168.1.53
      - 1.1.1.1
    environment:
      JWT_SECRET: <CHANGEME_SUPERSECRET>
      USER_SECRET: <CHANGEME_USERSALT>
      LOGIN_USERNAME: portnote_admin
      LOGIN_PASSWORD: "YourStrongPassword"
      DATABASE_URL: postgres://postgres:postgres@portnote-db:5432/postgres
    networks:
      portnote_internet_ui_net:
        ipv4_address: 192.168.128.2
    ports:
      - "4000:3000"
    depends_on:
      portnote-db:
        condition: service_healthy
```

And now it starts properly and I could access port 4000 and load the app, configure my server and autoscan the ports.

It all works, allthough is missing some ports.
